name: Cleanup Workflows

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      
      - name: Remove unwanted workflow files
        run: |
          # Remove the incomplete bootstrap workflow
          if [ -f ".github/workflows/bootstrap-complete.yml" ]; then
            rm .github/workflows/bootstrap-complete.yml
            echo "Removed bootstrap-complete.yml"
          fi
          
          # Remove this cleanup file itself after running
          rm .github/workflows/cleanup.yml
          rm .github/workflows/delete-marker.txt
          
          echo "Cleanup completed"
      
      - name: Commit cleanup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: remove incomplete workflow files"
            git push
          fi